server.port=8081

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://techtechnova131_db_user:Cluster123@cluster0.cj95fyl.mongodb.net/Aimodel?retryWrites=true&w=majority&ssl=true
spring.data.mongodb.database=Aimodel

# CORS Configuration
spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*